apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: letsencrypt
    server: {{ .Values.letsencryptDirectoryUrl }}
    solvers: 
      - dns01:
          webhook:
            config: eu-west-2
              apiKeySecretRef:
                name: godaddy-api-key
                key: token
              production: true
              ttl: 600
            groupName: acme.{{ .values.godaddyDomain }}
            solverName: godaddy