apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
data:
  prometheus.yml: |+

    global:
      scrape_timeout:      60s # Set the scrape interval to every 30 seconds. Default is every 10 secs.
      scrape_interval:     180s # Set the scrape interval to every 60 seconds. Default is every 1 minute.
      evaluation_interval: 60s # Evaluate rules every 60 seconds. The default is every 1 minute.
      external_labels:
        environment: production

    scrape_configs:
      - job_name: prometheus
        honor_labels: true
        static_configs:
          - targets:
            - localhost:9090
        metrics_path: /metrics

